sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm install -g codeclimate-test-reporter
script: npm run cover:report
after_script:
  - codeclimate-test-reporter < coverage.lcov
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
